version: '3'

services:
    mysql:
        build: docker/mysql
        ports:
            - 3307:3306
        restart: always
        volumes:
            - ./docker/data/mysql:/var/lib/mysql:delegated,rw
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: app
            MYSQL_USER: app
            MYSQL_PASSWORD: secret
        networks:
            - app
    php:
        image: webdevops/php-nginx-dev:7.3
        working_dir: /app
        restart: always
        volumes:
            - ./:/app:rw,cached
        environment:
            WEB_DOCUMENT_ROOT: /app/public
        networks:
            - app
        ports:
            - "8080:80"

networks:
    app:
        driver: bridge

volumes:
    data:
        driver: local
